version: "3.2"
services:
    db:
      image: mysql:5.7
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: hh
        MYSQL_USER: root
        MYSQL_PASSWORD: password

      ports:
        - 3307:3306

    app:
      depends_on:
        - db
      build: ./
      command: npm start
      volumes:
        - ./:/var/www/app 
      ports:
        - 3000:3000

volumes:
    db_data: {}